### ISSUE TITLE
How can I create the Semantic JSON FIle

### ISSUE THREAD

**Issue by dazmahal** [xBimTeam/XbimWebUI#3]
Hi - I've downloaded WBIM WebUI & XBim Exchange modules - I had to change the Nuget refereence as they were referencing 3.0.5 PreRelease, so I changed to 3.0.3 and all building ok now.

I have converted my IFC Model to .wexbim but how can I create the expected .json file
There is no link to COBieJSONSerialiser from the COBie Client?

Thanks
Daz

**Comment by martin1cerny** [comment]
I'm sorry you have this kind of trouble. We are unifying this part of the toolkit so that all data transformations are on one place. Fot now you need to reference Xbim.COBieLite project from XbimExchange and than use this code:

    using (var model = new XbimModel())
    {
    	model.CreateFrom(fileName, null, null, true);
    	var cobieFileName = "semantics.json";
    	using (var cobieFile = new FileStream(cobieFileName, FileMode.Create))
    	{
    		var helper = new CoBieLiteHelper(model, "UniClass");
    		var facility = helper.GetFacilities().FirstOrDefault();
    		if (facility != null)
    		{
    			using (var writer = new StreamWriter(cobieFile))
    			{
    				CoBieLiteHelper.WriteJson(writer, facility);
    				writer.Close();
    			}
    		}
    	}
    	
    	model.Close();
    }

I hope this helps

Martin

**Comment by dazmahal** [comment]
Thanks Martin
That worked well - This enabled me to create the semantics.json file without issue. I have also created the .wexbim without issue.
However when i navigate to the model I'm getting an exception in xbim-model-geometry.debug.js:32 Uncaught Magic number mismatch.

The value in binReader is not as expected - 3664129?

Thanks
Daz

![image](https://cloud.githubusercontent.com/assets/6757134/6048614/720651e0-aca9-11e4-82d5-f49d2f727238.png)

**Comment by martin1cerny** [comment]
We had an issue with geometry engine where some changes didn't make it
through from Codeplex to GitHub. If you get the latest version of
XbimGeometry you should be all right. We fixed this just two days ago.
Dne 4. 2. 2015 21:15 "daz" <notifications@github.com> napsal(a):

**Comment by dazmahal** [comment]
I have created the .wexbim and corresponding semantic json file usijng latest Geometry Code and got passed the above error to the point indicated below- Model still not loading - Sematic data is.. Any additional fixes I should be aware off?

![image](https://cloud.githubusercontent.com/assets/6757134/6135846/daaa8e5a-b163-11e4-9aea-90a4ff89eac4.png)

Many thanks

**Comment by martin1cerny** [comment]
Please make sure you use the latest Xplorer and WeXplorer. Also try to
clear your browser cache. If it doesn't help, can you provide us with your
IFC model? I can check if it works in my environment.
Dne 10. 2. 2015 21:32 "daz" <notifications@github.com> napsal(a):

**Comment by dazmahal** [comment]
Hi Martin
I'm using all of the latest Nuget Packages, problem persists. I had sent the model via dropbox to your profile on codeplex https://www.codeplex.com/site/users/contact/martin1cerny?OriginalUrl=http://www.codeplex.com/site/users/view/martin1cerny - Due to Confidentially I cant post it here publicly.
If you can try it in your environment that would be really useful.
Thanks

**Comment by dazmahal** [comment]
Alternatively if you wish to contact me on dazmahal@gmail.com I can send
the model directly. Thanks

**Comment by bhavneetsinghthakur** [comment]
Hi..martin1cerny  same problem i got in WindowsUI ==> Export

**Comment by dazmahal** [comment]
Hi Martin, With the support you have provided on this and also the latest enhancements to functionality in XBIM Exchange - This issue can be closed. Larger models are much more responsive, still recommend running in 64 Bit Allocation - makes the application much more responsive.
Many thanks
Darren
