### ISSUE TITLE
Archicad IFC  wrong behavior in the XbimWebUI

### ISSUE THREAD

**Issue by untecnologo** [xBimTeam/XbimWebUI#438]
We have noticed that when the IFC model is exported from Archicad, some elements have unexpected behavior, even when we are by code verifying that they are present in the 3D model.

There is a file attached in the below link.
https://file.io/LML93RL5LibH

This file in the viewer just shows the window:
![Window](https://github.com/xBimTeam/XbimWebUI/assets/37328540/0106311c-d40c-4424-a19b-41d4b94c4625)

But also there is a wall that the viewer is not showing. 

Do you have any solution, or have you noticed this before?

We can reproduce this if the file comes from an Archicad IFC exporter. 

Thank you in advance for your kind support!

**Comment by andyward** [comment]
How are you generating the wexbim - can you show the code? I've just tested and it renders fine:

<img width="1196" alt="image" src="https://github.com/xBimTeam/XbimWebUI/assets/923699/2c936952-78db-4e82-ab97-35ace67378fb">

Looking at the model, the Wall is modelled as an assembly/aggregation of multiple BuildingElementParts (representing the different layers in the wall). So the wall itself has no representation - it's all in the children. My guess is that somehow this is being overlooked in your wexbim generation, or the Geometry generation. 

Here's the [canonical way of creating wexbim](https://docs.xbim.net/examples/creating-wexbim-file.html). Are you doing something different?

**Comment by untecnologo** [comment]
![image](https://github.com/xBimTeam/XbimWebUI/assets/37328540/934a526a-2646-4156-b0df-4484a5c34abe)

Hello @andyward 
This is the code that creates the wexBim. 
All our files work fine, but for this specific case, it doesn't work as expected.

**Comment by andyward** [comment]
Thanks, so I have confirmed that's an issue in the latest v5.1 code, and is reproducible in wexbim/web viewer and in Windows UI. It's been broken for a long while - since 5.1.239 GE. 

It's needs some analysis to see if it's an issue in the Tessellator or the Geometry.

The good news is it's fixed in v6 (albeit with some warnings, which may indicate why it has been failing). Let me know if you want a preview of v6.

**Comment by untecnologo** [comment]
Thank you very much for your reply. 
I appreciate it.  
We are in the middle of a feature development and all the feature run and use version 5.
For now, we will keep version 5 because we are almost at the end of the module.
But as soon as V6 is released in the nugget package we will be happy to update our project.
We need also V6 because, in that version, the issue of the DLL creation is fixed.

https://github.com/xBimTeam/XbimGeometry/issues/455

**Comment by untecnologo** [comment]
Hi @andyward,
I have considered your proposal about the V6 of the plugin. After having too many issues with the topic we discussed here, I would like to have the opportunity to upgrade to V6 please let me know what I need to do or the repository link to access the V6.

Thank you in advance for your kind support.
Best regards,

**Comment by andyward** [comment]
Hi do you want to email me (email on my GH profile) and I'll get you invited to the preview nuget feed?

**Comment by untecnologo** [comment]
Done! I really appreciate it!

**Comment by spcaala** [comment]
Hi @andyward,

Thanks for looking into the issue and providing some pointers. 

However, we still have this issue with the viewer not recognising and visualising walls from Archicad IFC models to be specific and some revit models. @untecnologo never did get access to the nuget preview feed, so we were not able to verify your suggestion. 

However, we found a link from [Issue 526 ](https://github.com/xBimTeam/XbimEssentials/issues/526)to your myget resources and were able to get the latest develop for xbim essentials.  

This solved one of the issues we were having with some models not being converted to WexBim, however, the invisible wall is still a problem. 

xbim.geometry is still v5.1.742 and this all we can see from the resources link. Not sure if we are missing something. 

Is there a separate resource link for xbim geometry ? 

Here is screen shot all the updated packages. 
![image](https://github.com/xBimTeam/XbimWebUI/assets/94357458/39460083-89e1-4432-8e74-e50290e69ced)
![image](https://github.com/xBimTeam/XbimWebUI/assets/94357458/2ede9277-5991-4491-b2a7-52c7e015331d)

For context:
Our project is .net48 

Thanks for your time. Appreciate it.
